version: "3"

services:
  client-ui:
    build:
      context: ./client-ui
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    networks:
      - spring-cloud-network
      
  deal-service:
    build:
      context: ./deal-service
      dockerfile: ./Dockerfile
    ports:
      - 9001:9001
    networks:
      - spring-cloud-network
      
  comment-service:
    build:
      context: ./comment-service
      dockerfile: ./Dockerfile
    ports:
      - 9002:9002
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge