version: "3.8"

services:

  config-server:
    build:
      context: ./servers/config-server
      dockerfile: ./Dockerfile
    env_file:
      - env.list
    ports:
      - 9100:9100
    networks:
      - back-network

  eureka-server:
    build:
      context: ./servers/eureka-server
      dockerfile: ./Dockerfile
    ports:
      - 9102:9102
    networks:
      - back-network
    command: 
      sh -c "chmod +x wait-for-it.sh && apk add --no-cache bash && ./wait-for-it.sh config-server:9100 && java -jar /eureka-server.jar"
      
  zuul-server:
    build:
      context: ./servers/zuul-server
      dockerfile: ./Dockerfile
    ports:  
      - 8762:9004
    networks:
      - back-network
    depends_on:
      - eureka-server
    command: 
      sh -c "chmod +x wait-for-it.sh && apk add --no-cache bash && ./wait-for-it.sh eureka-server:9102 && java -jar /zuul-server.jar"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9100
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:9102/eureka
      
  client-ui:
    build:
      context: ./services/client-ui
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    networks:
      - back-network
      - front-network
    depends_on:
      - eureka-server
      - zuul-server
    command: 
      sh -c "chmod +x wait-for-it.sh && apk add --no-cache bash && ./wait-for-it.sh eureka-server:9102 && java -jar /client-ui.jar"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9100
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:9102/eureka
      
  deal-service:
    build:
      context: ./services/deal-service
      dockerfile: ./Dockerfile
    ports:
      - 9001:9001
    networks:
      - back-network
    depends_on:
      - eureka-server
      - zuul-server
    command: 
      sh -c "chmod +x wait-for-it.sh && apk add --no-cache bash && ./wait-for-it.sh eureka-server:9102 && java -jar /deal-service.jar"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9100
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:9102/eureka
      
  comment-service:
    build:
      context: ./services/comment-service
      dockerfile: ./Dockerfile
    ports:
      - 9002:9002
    networks:
      - back-network
    depends_on:
      - eureka-server
      - zuul-server
    command: 
      sh -c "chmod +x wait-for-it.sh && apk add --no-cache bash && ./wait-for-it.sh eureka-server:9102 && java -jar /comment-service.jar"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9100
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:9102/eureka

  dealabs-ui:
    build:
      context: ./dealabs-ui
      dockerfile: ./Dockerfile
    ports:
      - 3200:80
    networks:
      - back-network
      - front-network
    depends_on:
      - client-ui
     
networks:
  back-network:
    driver: bridge
  front-network:
    driver: bridge