version: "3.8"

services:

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: ./Dockerfile
    ports:
      - 9102:9102
    networks:
      - back-network
      
  zuul-server:
    build:
      context: ./zuul-server
      dockerfile: ./Dockerfile
    ports:  
      - 8762:9004
    networks:
      - back-network
      - config-server-network
    depends_on:
      - eureka-server
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9100
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:9102/eureka
      
  client-ui:
    build:
      context: ./client-ui
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    networks:
      - back-network
      - front-network
      - config-server-network
    depends_on:
      - eureka-server
      - zuul-server
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9100
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:9102/eureka
      
  deal-service:
    build:
      context: ./deal-service
      dockerfile: ./Dockerfile
    ports:
      - 9001:9001
    networks:
      - back-network
      - config-server-network
    depends_on:
      - eureka-server
      - zuul-server
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9100
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:9102/eureka
      
  comment-service:
    build:
      context: ./comment-service
      dockerfile: ./Dockerfile
    ports:
      - 9002:9002
    networks:
      - back-network
      - config-server-network
    depends_on:
      - eureka-server
      - zuul-server
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9100
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:9102/eureka

  dealabs-ui:
    build:
      context: ./dealabs-ui
      dockerfile: ./Dockerfile
    ports:
      - 3200:80
    networks:
      - back-network
      - front-network
      - config-server-network
    depends_on:
      - client-ui
     
networks:
  back-network:
    driver: bridge
  front-network:
    driver: bridge
  config-server-network:
    external: true