DROP TABLE IF EXISTS USER cascade;
DROP TABLE IF EXISTS ROLE cascade;
DROP TABLE IF EXISTS USER_ROLES cascade;

CREATE TABLE USER
(
    ID INT NOT NULL AUTO_INCREMENT, PRIMARY KEY (ID),
    username VARCHAR(255),
    password VARCHAR(255),
    email VARCHAR(255)
);

CREATE TABLE ROLE
(
    ID INT NOT NULL AUTO_INCREMENT, PRIMARY KEY (ID),
    name VARCHAR(255)
);